### ISSUE TITLE
"who is steve jobs/elon musk" got played but returns an error in the log

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/skill-ovos-wikipedia#12]
```
2023-04-19 10:58:55.100 - skills - mycroft.skills.intent_service:_normalize_all_utterances:61 - DEBUG - Utterances: [('who is elon musk',)]
2023-04-19 10:58:55.176 - skills - mycroft.skills.intent_services.padatious_service:_match_level:87 - DEBUG - Padatious Matching confidence > 0.95
2023-04-19 10:58:55.184 - skills - mycroft.skills.intent_services.commonqa_service:handle_question:119 - INFO - Searching for who is elon musk
2023-04-19 10:58:58.512 - skills - mycroft.skills.intent_services.commonqa_service:handle_query_response:152 - INFO - Answer from skill-ovos-wikipedia.openvoiceos
2023-04-19 10:58:58.514 - skills - mycroft.skills.intent_services.commonqa_service:_query_timeout:173 - INFO - Timeout occurred check responses
2023-04-19 10:58:58.523 - skills - mycroft.skills.intent_services.commonqa_service:_query_timeout:199 - INFO - Handling with: skill-ovos-wikipedia.openvoiceos

2023-04-19 10:58:58.606 - skills - ovos_workshop.skills.base:_on_event_error:1324 - ERROR - 'title'
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_utils/messagebus.py", line 543, in wrapper
    handler(message)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/common_query_skill.py", line 182, in __handle_query_action
    self.CQS_action(phrase, data)
  File "/home/ovos/.venv/lib/python3.11/site-packages/skill_ovos_wikipedia/__init__.py", line 102, in CQS_action
    self.set_context("WikiKnows", data["title"])
                                  ~~~~^^^^^^^^^
KeyError: 'title'
```

**Comment by JarbasAl** [comment]
https://github.com/OpenVoiceOS/skill-ovos-wikipedia/pull/11
