### ISSUE TITLE
ERROR - 'query'

### ISSUE THREAD

**Issue by atd** [OpenVoiceOS/skill-ovos-wikipedia#15]
Sometimes I get this error (`es-es` locale):

```
2023-05-15 18:38:22.260 - OVOS - ovos_bus_client.session:reset_default_session:191 - INFO - New Default Session Start: d32e0bdd-6260-425d-befe-8c513908412c
2023-05-15 18:38:22.432 - OVOS - ovos_utils.file_utils:resolve_resource_file:145 - WARNING - Expected a dict config and got None. This configfallback behavior will be deprecated in a future release
2023-05-15 18:38:22.458 - skill-ovos-wikipedia.openvoiceos - ERROR - 'query'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ovos_utils/messagebus.py", line 554, in wrapper
    handler(message)
  File "/home/ovos/.local/lib/python3.11/site-packages/skill_ovos_wikipedia/__init__.py", line 60, in handle_search
    self.current_title = query = message.data["query"]
                                 ~~~~~~~~~~~~^^^^^^^^^
KeyError: 'query'
```

I am a bit confused because https://github.com/OpenVoiceOS/skill-ovos-wikipedia/blob/dev/locale/en-us/searching.dialog has double braces, but https://github.com/OpenVoiceOS/skill-ovos-wikipedia/blob/dev/locale/es-es/searching.dialog doesn't. But looking at other `dialog` files, they usually have single braces :thinking:

**Comment by JarbasAl** [comment]
please re-open if still present, skill has been heavily refactored since
